@OrleansSamples.AspireBasic.Silo_HostAddress = https://localhost:7017

GET {{OrleansSamples.AspireBasic.Silo_HostAddress}}/account/1234
Accept: application/json

###

POST {{OrleansSamples.AspireBasic.Silo_HostAddress}}/account/1234/deposit
Accept: application/json
Content-Type: application/json

{
  "amount": 54321.24
}

###


POST {{OrleansSamples.AspireBasic.Silo_HostAddress}}/account/1234/withdraw
Accept: application/json
Content-Type: application/json

{
  "amount": 1000.23
}
